[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"

# Optional: proxy API requests to your backend to avoid CORS/config changes
# Replace the domain below after backend is deployed (Render/Railway/etc.)
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-DOMAIN.TLD/:splat"
  status = 200
  force = true

