services:
  - type: web
    name: djscovery-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      # After first deploy, set these in Render Dashboard with real values:
      - key: JWT_SECRET
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_FALLBACK_PLAYLIST_ID
        value: 1pSy9kzEtp4El0Op5CV8pf
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_LIST_ID
        sync: false
      - key: BREVO_USE_DOI
        value: "true"
      - key: BREVO_DOI_TEMPLATE_ID
        sync: false
      - key: BREVO_REDIRECT_URL
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: RECAPTCHA_MIN_SCORE
        value: "0.5"
      - key: ADMIN_EMAILS
        sync: false

